/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.swing.JOptionPane;
import util.koneksi;
import util.PasswordUtil;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author Lenovo
 */
public class Registrasi extends javax.swing.JFrame {

    /**
     * Creates new form Registrasi
     */
    public Registrasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNamaLengkap = new javax.swing.JTextField();
        txtNoTelepon = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtKonfirmasiPassword = new javax.swing.JPasswordField();
        btnBuatAkun = new javax.swing.JButton();
        btnKeLogin = new javax.swing.JLabel();
        BG_Registrasi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamaLengkap.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNamaLengkap.setBorder(null);
        jPanel1.add(txtNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 372, 470, 30));

        txtNoTelepon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNoTelepon.setBorder(null);
        jPanel1.add(txtNoTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 555, 470, 30));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 462, 470, 30));

        txtPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 647, 470, 30));

        txtKonfirmasiPassword.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtKonfirmasiPassword.setBorder(null);
        jPanel1.add(txtKonfirmasiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 737, 470, 30));

        btnBuatAkun.setBorder(null);
        btnBuatAkun.setBorderPainted(false);
        btnBuatAkun.setContentAreaFilled(false);
        btnBuatAkun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatAkunActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuatAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 827, 280, 50));

        btnKeLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeLoginMouseClicked(evt);
            }
        });
        jPanel1.add(btnKeLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 892, 50, 20));

        BG_Registrasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Registrasi.png"))); // NOI18N
        jPanel1.add(BG_Registrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuatAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatAkunActionPerformed
        // TODO add your handling code here:
        // 1. Ambil semua input dari form
        String namaLengkap = txtNamaLengkap.getText();
        String email = txtEmail.getText();
        String noTelepon = txtNoTelepon.getText();
        String password = new String(txtPassword.getPassword());
        String konfirmasiPassword = new String(txtKonfirmasiPassword.getPassword());

        // 2. Validasi Input
        if (namaLengkap.isEmpty() || email.isEmpty() || noTelepon.isEmpty() || password.isEmpty() || konfirmasiPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!password.equals(konfirmasiPassword)) {
            JOptionPane.showMessageDialog(this, "Password dan Konfirmasi Password tidak cocok!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Connection conn = koneksi.getKoneksi();
            
            // Cek apakah email/username sudah terdaftar
            String checkSql = "SELECT COUNT(*) FROM PENGGUNA WHERE email = ? OR nama_pengguna = ?";
            PreparedStatement checkPstmt = conn.prepareStatement(checkSql);
            checkPstmt.setString(1, email);
            checkPstmt.setString(2, email); // Asumsi username = email untuk pendaftaran baru
            ResultSet rs = checkPstmt.executeQuery();
            if(rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(this, "Email sudah terdaftar. Silakan gunakan email lain.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Insert data ke database
            String sql = "INSERT INTO PENGGUNA (nama_lengkap, email, telepon, kata_sandi, nama_pengguna, peran, aktif) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            
            pstmt.setString(1, namaLengkap);
            pstmt.setString(2, email);
            pstmt.setString(3, noTelepon);
            
            // HASH password sebelum disimpan untuk keamanan
            String hashedPassword = PasswordUtil.hashPassword(password);
            pstmt.setString(4, hashedPassword); // Simpan password yang sudah di-hash 
            
            pstmt.setString(5, email); // Jadikan email sebagai username default
            pstmt.setString(6, "Kasir"); // Tentukan peran default untuk pengguna baru
            pstmt.setBoolean(7, true);

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Registrasi berhasil! Silakan login.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            
            // Kembali ke form login
            new Login().setVisible(true);
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat registrasi: " + e.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuatAkunActionPerformed

    private void btnKeLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeLoginMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKeLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_Registrasi;
    private javax.swing.JButton btnBuatAkun;
    private javax.swing.JLabel btnKeLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtKonfirmasiPassword;
    private javax.swing.JTextField txtNamaLengkap;
    private javax.swing.JTextField txtNoTelepon;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
