/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ManajemenDiskon;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import util.koneksi;

/**
 *
 * @author Lenovo
 */
public class AddEditDiscountDialog extends javax.swing.JDialog {

    private int discountId;

    /**
     * Creates new form AddEditDiscountDialog
     */
    public AddEditDiscountDialog(java.awt.Frame parent, boolean modal, int discountId) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(parent);
        this.discountId = discountId;

        if (this.discountId > 0) {
            this.setTitle("Edit Diskon");
            loadDiscountData();
        } else {
            this.setTitle("Tambah Diskon Baru");
        }
    }

    private void loadDiscountData() {
        String sql = "SELECT * FROM DISKON WHERE id_diskon = ?";
        try (Connection conn = koneksi.getKoneksi(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, this.discountId);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                txtNamaDiskon.setText(rs.getString("nama_diskon"));
                cmbTipe.setSelectedItem(rs.getString("tipe_diskon"));
                spnNilai.setValue(rs.getBigDecimal("nilai"));
                dateAwal.setDate(rs.getDate("mulai_berlaku"));
                dateAkhir.setDate(rs.getDate("akhir_berlaku"));
                chkAktif.setSelected(rs.getBoolean("aktif"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data diskon: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JUDUL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNamaDiskon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbTipe = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spnNilai = new javax.swing.JSpinner();
        chkAktif = new javax.swing.JCheckBox();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        dateAkhir = new com.toedter.calendar.JDateChooser();
        dateAwal = new com.toedter.calendar.JDateChooser();
        BG_FormDiskon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JUDUL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        JUDUL.setForeground(new java.awt.Color(255, 255, 255));
        JUDUL.setText("Form Tambah Diskon");
        jPanel1.add(JUDUL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 43, -1, 50));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        txtNamaDiskon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNamaDiskon.setBorder(null);
        jPanel1.add(txtNamaDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 182, 320, 30));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        cmbTipe.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "persen", "nominal" }));
        cmbTipe.setBorder(null);
        jPanel1.add(cmbTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 242, 350, 40));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 20, 20));

        spnNilai.setBorder(null);
        jPanel1.add(spnNilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 307, 350, 40));

        chkAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAktifActionPerformed(evt);
            }
        });
        jPanel1.add(chkAktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 603, -1, 20));

        btnSimpan.setBorderPainted(false);
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 660, 170, 40));

        btnBatal.setBorderPainted(false);
        btnBatal.setContentAreaFilled(false);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 663, 170, 30));
        jPanel1.add(dateAkhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 350, 40));
        jPanel1.add(dateAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 372, 350, 40));

        BG_FormDiskon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Form Diskon.png"))); // NOI18N
        jPanel1.add(BG_FormDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        // Validasi input
        if (txtNamaDiskon.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama diskon tidak boleh kosong.");
            return;
        }

        // PERBAIKAN 1: Menggunakan JDateChooser untuk mengambil tanggal
        java.util.Date tglMulai = dateAwal.getDate();
        java.util.Date tglAkhir = dateAkhir.getDate();

        if (tglMulai == null || tglAkhir == null) {
            JOptionPane.showMessageDialog(this, "Tanggal mulai dan akhir harus diisi.");
            return;
        }
        
        // Konversi dari java.util.Date ke java.sql.Date
        Date sqlTglMulai = new Date(tglMulai.getTime());
        Date sqlTglAkhir = new Date(tglAkhir.getTime());


        try (Connection conn = koneksi.getKoneksi()) {
            PreparedStatement pstmt;
            if (this.discountId == 0) { // Mode Tambah
                String sql = "INSERT INTO DISKON (nama_diskon, tipe_diskon, nilai, mulai_berlaku, akhir_berlaku, aktif, id_pengguna_pembuat) VALUES (?, ?, ?, ?, ?, ?, ?)";
                pstmt = conn.prepareStatement(sql);
                // Ganti dengan ID user yang sedang login dari UserSession
                pstmt.setInt(7, util.UserSession.getInstance().getIdPengguna()); 
            } else { // Mode Edit
                String sql = "UPDATE DISKON SET nama_diskon=?, tipe_diskon=?, nilai=?, mulai_berlaku=?, akhir_berlaku=?, aktif=? WHERE id_diskon=?";
                pstmt = conn.prepareStatement(sql);
                pstmt.setInt(7, this.discountId);
            }

            pstmt.setString(1, txtNamaDiskon.getText());
            pstmt.setString(2, (String) cmbTipe.getSelectedItem());
            pstmt.setBigDecimal(3, new BigDecimal(spnNilai.getValue().toString()));
            
            // Set tanggal menggunakan objek java.sql.Date yang sudah dikonversi
            pstmt.setDate(4, sqlTglMulai);
            pstmt.setDate(5, sqlTglAkhir);
            
            pstmt.setBoolean(6, chkAktif.isSelected());
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data diskon berhasil disimpan!");
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data diskon: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void chkAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAktifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAktifActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        DiscountManagementForm DMForm = new DiscountManagementForm(); DMForm.setVisible(true);
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_FormDiskon;
    private javax.swing.JLabel JUDUL;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JCheckBox chkAktif;
    private javax.swing.JComboBox<String> cmbTipe;
    private com.toedter.calendar.JDateChooser dateAkhir;
    private com.toedter.calendar.JDateChooser dateAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner spnNilai;
    private javax.swing.JTextField txtNamaDiskon;
    // End of variables declaration//GEN-END:variables
}
