/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ManajemenDiskon;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import util.koneksi;

/**
 *
 * @author Lenovo
 */
public class AddEditDiscountDialog extends javax.swing.JDialog {

    private int discountId;

    /**
     * Creates new form AddEditDiscountDialog
     */
    public AddEditDiscountDialog(java.awt.Frame parent, boolean modal, int discountId) {
        super(parent, modal);
        initComponents();

        this.setLocationRelativeTo(parent);
        this.discountId = discountId;

        if (this.discountId > 0) {
            this.setTitle("Edit Diskon");
            loadDiscountData();
        } else {
            this.setTitle("Tambah Diskon Baru");
        }
    }

    private void loadDiscountData() {
        String sql = "SELECT * FROM DISKON WHERE id_diskon = ?";
        try (Connection conn = koneksi.getKoneksi(); PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, this.discountId);
            ResultSet rs = pstmt.executeQuery();
            if (rs.next()) {
                txtNamaDiskon.setText(rs.getString("nama_diskon"));
                cmbTipe.setSelectedItem(rs.getString("tipe_diskon"));
                spnNilai.setValue(rs.getBigDecimal("nilai"));
                txtTanggalMulai.setText(rs.getDate("mulai_berlaku").toString());
                txtTanggalAkhir.setText(rs.getDate("akhir_berlaku").toString());
                chkAktif.setSelected(rs.getBoolean("aktif"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data diskon: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNamaDiskon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbTipe = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTanggalMulai = new javax.swing.JTextField();
        txtTanggalAkhir = new javax.swing.JTextField();
        spnNilai = new javax.swing.JSpinner();
        chkAktif = new javax.swing.JCheckBox();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nama Diskon");

        jLabel2.setText("Tipe");

        cmbTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "persen", "nominal" }));

        jLabel3.setText("Nilai");

        jLabel4.setText("Tanggal Mulai");

        jLabel5.setText("Tanggal Akhir");

        txtTanggalMulai.setToolTipText("YYYY-MM-DD");

        txtTanggalAkhir.setToolTipText("YYYY-MM-DD");

        chkAktif.setText("Aktifkan Diskon Ini");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNamaDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spnNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(txtTanggalMulai))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(txtTanggalAkhir)))
                    .addComponent(chkAktif, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNamaDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cmbTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnNilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTanggalMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTanggalAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(chkAktif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        // Validasi input
        if (txtNamaDiskon.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama diskon tidak boleh kosong.");
            return;
        }

        try (Connection conn = koneksi.getKoneksi()) {
            PreparedStatement pstmt;
            if (this.discountId == 0) { // Mode Tambah
                String sql = "INSERT INTO DISKON (nama_diskon, tipe_diskon, nilai, mulai_berlaku, akhir_berlaku, aktif, id_pengguna_pembuat) VALUES (?, ?, ?, ?, ?, ?, ?)";
                pstmt = conn.prepareStatement(sql);
            } else { // Mode Edit
                String sql = "UPDATE DISKON SET nama_diskon=?, tipe_diskon=?, nilai=?, mulai_berlaku=?, akhir_berlaku=?, aktif=? WHERE id_diskon=?";
                pstmt = conn.prepareStatement(sql);
                pstmt.setInt(7, this.discountId);
            }

            pstmt.setString(1, txtNamaDiskon.getText());
            pstmt.setString(2, (String) cmbTipe.getSelectedItem());
            pstmt.setBigDecimal(3, new BigDecimal(spnNilai.getValue().toString()));
            pstmt.setDate(4, Date.valueOf(txtTanggalMulai.getText())); // Format YYYY-MM-DD
            pstmt.setDate(5, Date.valueOf(txtTanggalAkhir.getText()));
            pstmt.setBoolean(6, chkAktif.isSelected());
            if (this.discountId == 0) {
                pstmt.setInt(7, 1); // Ganti dengan ID user login
            }
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data diskon berhasil disimpan!");
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data diskon: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JCheckBox chkAktif;
    private javax.swing.JComboBox<String> cmbTipe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner spnNilai;
    private javax.swing.JTextField txtNamaDiskon;
    private javax.swing.JTextField txtTanggalAkhir;
    private javax.swing.JTextField txtTanggalMulai;
    // End of variables declaration//GEN-END:variables
}
