/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ManajemenDiskon;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.koneksi;

/**
 *
 * @author Lenovo
 */
public class DiscountManagementForm extends javax.swing.JFrame {

    private DefaultTableModel modelDiscounts;
    private DefaultTableModel modelProducts;

    /**
     * Creates new form DiscountManagementForm
     */
    public DiscountManagementForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Manajemen Diskon & Promosi");

        // Setup tabel diskon
        modelDiscounts = (DefaultTableModel) tblDiscounts.getModel();
        modelDiscounts.setColumnIdentifiers(new Object[]{"ID", "Nama Diskon", "Tipe", "Nilai"});

        // Setup tabel produk
        modelProducts = (DefaultTableModel) tblProducts.getModel();
        modelProducts.setColumnIdentifiers(new Object[]{"ID", "Nama Produk"});

        loadDiscounts();
        loadProducts();
    }

    private void loadDiscounts() {
        modelDiscounts.setRowCount(0);
        try (Connection conn = koneksi.getKoneksi(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT id_diskon, nama_diskon, tipe_diskon, nilai FROM DISKON")) {
            while (rs.next()) {
                modelDiscounts.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getBigDecimal(4)});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat diskon: " + e.getMessage());
        }
    }

    private void loadProducts() {
        modelProducts.setRowCount(0);
        try (Connection conn = koneksi.getKoneksi(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT id_produk, nama_produk FROM PRODUK ORDER BY nama_produk")) {
            while (rs.next()) {
                modelProducts.addRow(new Object[]{rs.getInt(1), rs.getString(2)});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat produk: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiscounts = new javax.swing.JTable();
        btnTambahDiskon = new javax.swing.JButton();
        btnEditDiskon = new javax.swing.JButton();
        btnHapusDiskon = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        btnApplyDiscount = new javax.swing.JButton();
        btnRemoveDiscount = new javax.swing.JButton();
        BG_DiskonManagement = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblDiscounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDiscounts);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 550, 620, -1));

        btnTambahDiskon.setBorderPainted(false);
        btnTambahDiskon.setContentAreaFilled(false);
        btnTambahDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDiskonActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambahDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 172, 240, 50));

        btnEditDiskon.setBorderPainted(false);
        btnEditDiskon.setContentAreaFilled(false);
        btnEditDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDiskonActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(942, 293, 240, 50));

        btnHapusDiskon.setBorderPainted(false);
        btnHapusDiskon.setContentAreaFilled(false);
        jPanel1.add(btnHapusDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 412, 240, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProducts);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 620, -1));

        btnApplyDiscount.setBorderPainted(false);
        btnApplyDiscount.setContentAreaFilled(false);
        btnApplyDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyDiscountActionPerformed(evt);
            }
        });
        jPanel1.add(btnApplyDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 650, 340, 60));

        btnRemoveDiscount.setBorderPainted(false);
        btnRemoveDiscount.setContentAreaFilled(false);
        btnRemoveDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDiscountActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemoveDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 750, 350, 60));

        BG_DiskonManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Manajemen Diskon.png"))); // NOI18N
        jPanel1.add(BG_DiskonManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyDiscountActionPerformed
        // TODO add your handling code here:
        int selectedDiscountRow = tblDiscounts.getSelectedRow();
        int[] selectedProductRows = tblProducts.getSelectedRows();

        if (selectedDiscountRow == -1 || selectedProductRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Pilih satu diskon dan minimal satu produk.");
            return;
        }

        int idDiskon = (int) tblDiscounts.getValueAt(selectedDiscountRow, 0);

        // INSERT IGNORE digunakan agar tidak terjadi error jika relasi sudah ada (duplicate entry)
        String sql = "INSERT IGNORE INTO DISKON_PRODUK (id_diskon, id_produk) VALUES (?, ?)";
        try (Connection conn = koneksi.getKoneksi(); PreparedStatement pstmt = conn.prepareStatement(sql)) {

            for (int row : selectedProductRows) {
                int idProduk = (int) tblProducts.getValueAt(row, 0);
                pstmt.setInt(1, idDiskon);
                pstmt.setInt(2, idProduk);
                pstmt.addBatch();
            }
            pstmt.executeBatch();
            JOptionPane.showMessageDialog(this, "Diskon berhasil diterapkan ke produk terpilih!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menerapkan diskon: " + e.getMessage());
        }
    }//GEN-LAST:event_btnApplyDiscountActionPerformed

    private void btnTambahDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDiskonActionPerformed
        // TODO add your handling code here:
        new AddEditDiscountDialog(this, true, 0).setVisible(true);
        loadDiscounts();
    }//GEN-LAST:event_btnTambahDiskonActionPerformed

    private void btnEditDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDiskonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDiscounts.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih diskon yang akan diedit.");
            return;
        }
        int discountId = (int) tblDiscounts.getValueAt(selectedRow, 0);
        new AddEditDiscountDialog(this, true, discountId).setVisible(true);
        loadDiscounts();
    }//GEN-LAST:event_btnEditDiskonActionPerformed

    private void btnRemoveDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDiscountActionPerformed
        // TODO add your handling code here:
        // 1. Dapatkan baris yang dipilih dari kedua tabel
        int selectedDiscountRow = tblDiscounts.getSelectedRow();
        int[] selectedProductRows = tblProducts.getSelectedRows();

        // 2. Validasi apakah pengguna sudah memilih diskon dan produk
        if (selectedDiscountRow == -1 || selectedProductRows.length == 0) {
            JOptionPane.showMessageDialog(this,
                    "Harap pilih satu diskon dan minimal satu produk yang diskonnya akan dihapus.",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. Dapatkan ID diskon yang dipilih untuk digunakan dalam query dan pesan konfirmasi
        int idDiskon = (int) tblDiscounts.getValueAt(selectedDiscountRow, 0);
        String namaDiskon = (String) tblDiscounts.getValueAt(selectedDiscountRow, 1);

        // 4. Minta konfirmasi dari pengguna sebelum menghapus
        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah Anda yakin ingin menghapus diskon '" + namaDiskon + "' dari produk yang dipilih?",
                "Konfirmasi Hapus Relasi Diskon",
                JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) {
            return; // Batalkan proses jika pengguna memilih 'Tidak'
        }

        // 5. Siapkan query SQL untuk menghapus data dari tabel relasi DISKON_PRODUK
        String sql = "DELETE FROM DISKON_PRODUK WHERE id_diskon = ? AND id_produk = ?";

        try (Connection conn = koneksi.getKoneksi(); PreparedStatement pstmt = conn.prepareStatement(sql)) {

            conn.setAutoCommit(false); // Mulai transaksi

            // 6. Lakukan iterasi untuk setiap produk yang dipilih
            for (int row : selectedProductRows) {
                int idProduk = (int) tblProducts.getValueAt(row, 0);

                // Set parameter untuk query DELETE
                pstmt.setInt(1, idDiskon);
                pstmt.setInt(2, idProduk);

                // Tambahkan perintah ke dalam batch
                pstmt.addBatch();
            }

            // 7. Eksekusi semua perintah dalam batch
            pstmt.executeBatch();
            conn.commit(); // Selesaikan transaksi jika semua berhasil

            JOptionPane.showMessageDialog(this,
                    "Diskon berhasil dihapus dari produk terpilih.",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            // Tampilkan pesan error jika terjadi kegagalan
            JOptionPane.showMessageDialog(this,
                    "Gagal menghapus diskon dari produk: " + e.getMessage(),
                    "Error Database",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveDiscountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiscountManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiscountManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiscountManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiscountManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiscountManagementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_DiskonManagement;
    private javax.swing.JButton btnApplyDiscount;
    private javax.swing.JButton btnEditDiskon;
    private javax.swing.JButton btnHapusDiskon;
    private javax.swing.JButton btnRemoveDiscount;
    private javax.swing.JButton btnTambahDiskon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblDiscounts;
    private javax.swing.JTable tblProducts;
    // End of variables declaration//GEN-END:variables
}
