/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ManajemenDiskon;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.koneksi;

/**
 *
 * @author Lenovo
 */
public class DiscountManagementForm extends javax.swing.JFrame {

    private DefaultTableModel modelDiscounts;
    private DefaultTableModel modelProducts;

    /**
     * Creates new form DiscountManagementForm
     */
    public DiscountManagementForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Manajemen Diskon & Promosi");

        // Setup tabel diskon
        modelDiscounts = (DefaultTableModel) tblDiscounts.getModel();
        modelDiscounts.setColumnIdentifiers(new Object[]{"ID", "Nama Diskon", "Tipe", "Nilai"});

        // Setup tabel produk
        modelProducts = (DefaultTableModel) tblProducts.getModel();
        modelProducts.setColumnIdentifiers(new Object[]{"ID", "Nama Produk"});

        loadDiscounts();
        loadProducts();
    }

    private void loadDiscounts() {
        modelDiscounts.setRowCount(0);
        try (Connection conn = koneksi.getKoneksi(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT id_diskon, nama_diskon, tipe_diskon, nilai FROM DISKON")) {
            while (rs.next()) {
                modelDiscounts.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getBigDecimal(4)});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat diskon: " + e.getMessage());
        }
    }

    private void loadProducts() {
        modelProducts.setRowCount(0);
        try (Connection conn = koneksi.getKoneksi(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT id_produk, nama_produk FROM PRODUK ORDER BY nama_produk")) {
            while (rs.next()) {
                modelProducts.addRow(new Object[]{rs.getInt(1), rs.getString(2)});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat produk: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDiscounts = new javax.swing.JTable();
        btnTambahDiskon = new javax.swing.JButton();
        btnEditDiskon = new javax.swing.JButton();
        btnHapusDiskon = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        btnApplyDiscount = new javax.swing.JButton();
        btnRemoveDiscount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblDiscounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDiscounts);

        btnTambahDiskon.setText("Tambah");
        btnTambahDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahDiskonActionPerformed(evt);
            }
        });

        btnEditDiskon.setText("Edit");
        btnEditDiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDiskonActionPerformed(evt);
            }
        });

        btnHapusDiskon.setText("Hapus");

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblProducts);

        btnApplyDiscount.setText("Terapkan Diskon ke Produk ");
        btnApplyDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyDiscountActionPerformed(evt);
            }
        });

        btnRemoveDiscount.setText("Hapus Diskon dari Produk");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditDiskon)
                    .addComponent(btnTambahDiskon)
                    .addComponent(btnHapusDiskon))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApplyDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(btnRemoveDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnTambahDiskon)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditDiskon)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusDiskon))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnApplyDiscount)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveDiscount)))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplyDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyDiscountActionPerformed
        // TODO add your handling code here:
        int selectedDiscountRow = tblDiscounts.getSelectedRow();
        int[] selectedProductRows = tblProducts.getSelectedRows();

        if (selectedDiscountRow == -1 || selectedProductRows.length == 0) {
            JOptionPane.showMessageDialog(this, "Pilih satu diskon dan minimal satu produk.");
            return;
        }

        int idDiskon = (int) tblDiscounts.getValueAt(selectedDiscountRow, 0);
        
        // INSERT IGNORE digunakan agar tidak terjadi error jika relasi sudah ada (duplicate entry)
        String sql = "INSERT IGNORE INTO DISKON_PRODUK (id_diskon, id_produk) VALUES (?, ?)";
        try (Connection conn = koneksi.getKoneksi();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
            for (int row : selectedProductRows) {
                int idProduk = (int) tblProducts.getValueAt(row, 0);
                pstmt.setInt(1, idDiskon);
                pstmt.setInt(2, idProduk);
                pstmt.addBatch();
            }
            pstmt.executeBatch();
            JOptionPane.showMessageDialog(this, "Diskon berhasil diterapkan ke produk terpilih!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menerapkan diskon: " + e.getMessage());
        }
    }//GEN-LAST:event_btnApplyDiscountActionPerformed

    private void btnTambahDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahDiskonActionPerformed
        // TODO add your handling code here:
        new AddEditDiscountDialog(this, true, 0).setVisible(true);
        loadDiscounts();
    }//GEN-LAST:event_btnTambahDiskonActionPerformed

    private void btnEditDiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDiskonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDiscounts.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih diskon yang akan diedit.");
            return;
        }
        int discountId = (int) tblDiscounts.getValueAt(selectedRow, 0);
        new AddEditDiscountDialog(this, true, discountId).setVisible(true);
        loadDiscounts();
    }//GEN-LAST:event_btnEditDiskonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiscountManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiscountManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiscountManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiscountManagementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiscountManagementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyDiscount;
    private javax.swing.JButton btnEditDiskon;
    private javax.swing.JButton btnHapusDiskon;
    private javax.swing.JButton btnRemoveDiscount;
    private javax.swing.JButton btnTambahDiskon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblDiscounts;
    private javax.swing.JTable tblProducts;
    // End of variables declaration//GEN-END:variables
}
