/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Profile;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import util.koneksi;

/**
 *
 * @author User
 */
public class EditProfile extends javax.swing.JFrame {
private int id_pengguna;
    /**
     * Creates new form EditProfile
     */
    public EditProfile() {
        initComponents();
        txtRole.setEnabled(false);     // Role tidak bisa diubah
    }
    
    public EditProfile(int id_pengguna) {
    this.id_pengguna = id_pengguna;
    initComponents();
    loadProfileData(id_pengguna); // Jika ingin load otomatis data pengguna
}

    public void loadProfileData(int id_pengguna) {
    try {
        Connection conn = koneksi.getKoneksi();
        String sql = "SELECT * FROM pengguna WHERE id_pengguna = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, id_pengguna);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            txtNamaLengkap.setText(rs.getString("nama_lengkap"));
            txtRole.setText(rs.getString("peran"));
            txtEmail.setText(rs.getString("email"));
            txtTelepon.setText(rs.getString("telepon"));
        }

        rs.close();
        ps.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data profil: " + e.getMessage());
    }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTelepon = new javax.swing.JTextField();
        txtNamaLengkap = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtRole = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        BG_EditProfile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTelepon.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTelepon.setBorder(null);
        jPanel1.add(txtTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 630, 470, 30));

        txtNamaLengkap.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNamaLengkap.setBorder(null);
        jPanel1.add(txtNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 407, 470, 30));

        txtEmail.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 557, 470, 30));

        txtRole.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(txtRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 470, 30));

        btnSimpan.setBorderPainted(false);
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 720, 160, 50));

        BG_EditProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Edit Profile v2.png"))); // NOI18N
        jPanel1.add(BG_EditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    try {
        Connection conn = koneksi.getKoneksi();
        String sql = "UPDATE pengguna SET nama_lengkap=?, peran=?, email=?, telepon=? WHERE id_pengguna=?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, txtNamaLengkap.getText());
        stmt.setString(2, txtRole.getText());
        stmt.setString(3, txtEmail.getText());
        stmt.setString(4, txtTelepon.getText());
        stmt.setInt(5, id_pengguna); // Pastikan variabel ini tersedia
        
        int updated = stmt.executeUpdate();
        if (updated > 0) {
            JOptionPane.showMessageDialog(this, "Profil berhasil disimpan!");
            
            // 🔁 Pindah ke halaman Profil
            Profile profilePage = new Profile(this); // this = halaman EditProfile

            profilePage.setVisible(true);
            this.dispose(); // Tutup halaman edit
        }

        stmt.close();
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_EditProfile;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNamaLengkap;
    private javax.swing.JLabel txtRole;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}