/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ManajemenInventori;

import util.koneksi;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class GoodsReceiptForm extends javax.swing.JFrame {

    private DefaultTableModel modelOpenOrders;
    private DefaultTableModel modelReceiptDetails;

    /**
     * Creates new form GoodsReceiptForm
     */
    public GoodsReceiptForm() {
        initComponents();

        this.setLocationRelativeTo(null);
        this.setTitle("Penerimaan Barang Masuk (Goods Receipt)");

        // Setup model untuk tabel pesanan terbuka
        modelOpenOrders = new DefaultTableModel();
        tblOpenOrders.setModel(modelOpenOrders);
        modelOpenOrders.setColumnIdentifiers(new Object[]{"ID PO", "Kode PO", "Nama Pemasok", "Tanggal Pesan"});

        // Setup model untuk tabel detail
        modelReceiptDetails = new DefaultTableModel();
        tblReceiptDetails.setModel(modelReceiptDetails);
        modelReceiptDetails.setColumnIdentifiers(new Object[]{"ID Produk", "Nama Produk", "Jumlah Dipesan"});

        // Tambahkan listener untuk mendeteksi saat pengguna memilih PO
        tblOpenOrders.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblOpenOrders.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            if (!event.getValueIsAdjusting() && tblOpenOrders.getSelectedRow() != -1) {
                int selectedRow = tblOpenOrders.getSelectedRow();
                int poId = (int) tblOpenOrders.getValueAt(selectedRow, 0);
                loadOrderDetails(poId);
            }
        });

        // Muat data awal
        loadOpenOrders();
    }

    private void loadOpenOrders() {
        modelOpenOrders.setRowCount(0);
        modelReceiptDetails.setRowCount(0); // Kosongkan juga tabel detail
        String sql = "SELECT p.id_pembelian, p.kode_pembelian, s.nama_pemasok, p.tanggal_beli "
                + "FROM PEMBELIAN p JOIN PEMASOK s ON p.id_pemasok = s.id_pemasok "
                + "WHERE p.status = 'Dipesan' ORDER BY p.tanggal_beli DESC";

        try (Connection conn = koneksi.getKoneksi(); PreparedStatement pstmt = conn.prepareStatement(sql); ResultSet rs = pstmt.executeQuery()) {

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy HH:mm");
            while (rs.next()) {
                modelOpenOrders.addRow(new Object[]{
                    rs.getInt("id_pembelian"),
                    rs.getString("kode_pembelian"),
                    rs.getString("nama_pemasok"),
                    dateFormat.format(rs.getTimestamp("tanggal_beli"))
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat daftar pesanan: " + e.getMessage());
        }
    }
    
    private void loadOrderDetails(int purchaseOrderId) {
        modelReceiptDetails.setRowCount(0);
        String sql = "SELECT d.id_produk, p.nama_produk, d.jumlah " +
                     "FROM DETAIL_PEMBELIAN d JOIN PRODUK p ON d.id_produk = p.id_produk " +
                     "WHERE d.id_pembelian = ?";
        
        try (Connection conn = koneksi.getKoneksi();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setInt(1, purchaseOrderId);
            ResultSet rs = pstmt.executeQuery();
            while(rs.next()) {
                modelReceiptDetails.addRow(new Object[]{
                    rs.getInt("id_produk"),
                    rs.getString("nama_produk"),
                    rs.getInt("jumlah")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat detail pesanan: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOpenOrders = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReceiptDetails = new javax.swing.JTable();
        btnConfirmReceipt = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Daftar Pesanan Pembelian (PO) yang Belum Diterima");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        tblOpenOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblOpenOrders);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel2.setText("Detail Barang untuk PO Terpilih");

        tblReceiptDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblReceiptDetails);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(230, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnConfirmReceipt.setText("Konfirmasi Penerimaan Barang");
        btnConfirmReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRefresh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnConfirmReceipt)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConfirmReceipt)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmReceiptActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblOpenOrders.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih sebuah Pesanan Pembelian (PO) dari tabel atas terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (JOptionPane.showConfirmDialog(this, "Anda yakin ingin mengonfirmasi penerimaan barang untuk PO ini? Stok akan diperbarui.", "Konfirmasi Penerimaan", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
            return;
        }

        int poId = (int) tblOpenOrders.getValueAt(selectedRow, 0);
        String poKode = (String) tblOpenOrders.getValueAt(selectedRow, 1);
        
        Connection conn = null;
        try {
            conn = koneksi.getKoneksi();
            conn.setAutoCommit(false); // Mulai transaksi untuk memastikan semua query berhasil

            // Loop melalui setiap item di tabel detail untuk memperbarui stok
            for (int i = 0; i < modelReceiptDetails.getRowCount(); i++) {
                int productId = (int) modelReceiptDetails.getValueAt(i, 0);
                int quantity = (int) modelReceiptDetails.getValueAt(i, 2);

                // 1. UPDATE stok di tabel PRODUK
                String sqlUpdateStok = "UPDATE PRODUK SET jumlah_stok = jumlah_stok + ? WHERE id_produk = ?";
                try (PreparedStatement pstmtUpdate = conn.prepareStatement(sqlUpdateStok)) {
                    pstmtUpdate.setInt(1, quantity);
                    pstmtUpdate.setInt(2, productId);
                    pstmtUpdate.executeUpdate();
                }

                // 2. INSERT riwayat ke tabel PERGERAKAN_STOK
                String sqlLog = "INSERT INTO PERGERAKAN_STOK (id_produk, tipe, jumlah, keterangan) VALUES (?, 'masuk', ?, ?)";
                try (PreparedStatement pstmtLog = conn.prepareStatement(sqlLog)) {
                    pstmtLog.setInt(1, productId);
                    pstmtLog.setInt(2, quantity);
                    pstmtLog.setString(3, "Penerimaan barang dari PO: " + poKode);
                    pstmtLog.executeUpdate();
                }
            }

            // 3. UPDATE status pesanan menjadi 'Diterima'
            String sqlUpdatePO = "UPDATE PEMBELIAN SET status = 'Diterima' WHERE id_pembelian = ?";
            try (PreparedStatement pstmtPO = conn.prepareStatement(sqlUpdatePO)) {
                pstmtPO.setInt(1, poId);
                pstmtPO.executeUpdate();
            }

            conn.commit(); // Jika semua berhasil, simpan perubahan ke database
            JOptionPane.showMessageDialog(this, "Penerimaan barang berhasil dikonfirmasi. Stok produk telah diperbarui.", "Sukses", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            try {
                if (conn != null) conn.rollback(); // Jika ada satu saja error, batalkan semua perubahan
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan fatal. Transaksi dibatalkan. Error: " + e.getMessage(), "Error Database", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } finally {
            try {
                if (conn != null) conn.setAutoCommit(true); // Kembalikan koneksi ke mode normal
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        
        loadOpenOrders(); // Muat ulang daftar pesanan
    }//GEN-LAST:event_btnConfirmReceiptActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        loadOpenOrders();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GoodsReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GoodsReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GoodsReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoodsReceiptForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GoodsReceiptForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnConfirmReceipt;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOpenOrders;
    private javax.swing.JTable tblReceiptDetails;
    // End of variables declaration//GEN-END:variables
}
