/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ManajemenProduk;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import ManajemenProduk.KategoriItem;
import java.sql.SQLException;
import util.koneksi;

/**
 *
 * @author Lenovo
 */
public class ProdukFormDialog extends javax.swing.JDialog {

    private int productId;

    /**
     * Creates new form ProdukFormDialog
     */
    public ProdukFormDialog(java.awt.Frame parent, boolean modal, int productId) {
        super(parent, modal);
        initComponents();

        this.pack();
        this.productId = productId;
        loadKategoriComboBox();

        if (productId > 0) {
            this.setTitle("Edit Produk");
            txtBarcode.setEditable(true); // Barcode bisa diedit jika mode edit
            loadProductData();
        } else {
            this.setTitle("Tambah Produk Baru");
            txtBarcode.setEditable(false); // Barcode tidak bisa diedit saat menambah
            txtBarcode.setText("(Akan Dibuat Otomatis)");
        }
    }

    private void loadKategoriComboBox() {
        DefaultComboBoxModel<KategoriItem> model = new DefaultComboBoxModel<>();
        try {
            Connection conn = koneksi.getKoneksi();
            Statement stmt = conn.createStatement();
            // Ambil id dan nama kategori dari tabel KATEGORI 
            ResultSet rs = stmt.executeQuery("SELECT id_kategori, nama_kategori FROM KATEGORI ORDER BY nama_kategori");

            while (rs.next()) {
                int id = rs.getInt("id_kategori");
                String nama = rs.getString("nama_kategori");
                // Tambahkan objek KategoriItem ke model JComboBox
                model.addElement(new KategoriItem(id, nama));
            }
            cmbKategori.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data kategori: " + e.getMessage());
        }
    }

    private void loadProductData() {
        try {
            Connection conn = koneksi.getKoneksi();
            PreparedStatement pstmt = conn.prepareStatement("SELECT * FROM PRODUK WHERE id_produk = ?");
            pstmt.setInt(1, this.productId);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                txtNamaProduk.setText(rs.getString("nama_produk"));
                txtBarcode.setText(rs.getString("kode_barcode"));
                txtHargaBeli.setText(rs.getString("harga_beli"));
                txtHargaJual.setText(rs.getString("harga_jual"));
                txtStok.setText(rs.getString("jumlah_stok"));
                txtStokMinimum.setText(rs.getString("stok_minimum"));

                int idKategoriProduk = rs.getInt("id_kategori");

                // Dapatkan model dari JComboBox yang sudah terisi
                DefaultComboBoxModel<KategoriItem> model = (DefaultComboBoxModel<KategoriItem>) cmbKategori.getModel();

                // Loop melalui setiap item di ComboBox untuk menemukan yang cocok
                for (int i = 0; i < model.getSize(); i++) {
                    // Cek apakah ID KategoriItem di dalam ComboBox sama dengan ID kategori produk
                    if (model.getElementAt(i).getId() == idKategoriProduk) {
                        // Jika ID-nya cocok, pilih item tersebut
                        cmbKategori.setSelectedIndex(i);
                        break; // Hentikan loop karena item sudah ketemu
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data produk: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNamaProduk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHargaBeli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbKategori = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtHargaJual = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStokMinimum = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        BG_FormProduk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(896, 746));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        txtNamaProduk.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNamaProduk.setBorder(null);
        jPanel2.add(txtNamaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 183, 320, 30));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        txtBarcode.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtBarcode.setBorder(null);
        jPanel2.add(txtBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 248, 320, 30));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        txtHargaBeli.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtHargaBeli.setBorder(null);
        txtHargaBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaBeliActionPerformed(evt);
            }
        });
        jPanel2.add(txtHargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 312, 320, 30));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        cmbKategori.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cmbKategori.setBorder(null);
        jPanel2.add(cmbKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 372, 350, 40));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        txtHargaJual.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtHargaJual.setBorder(null);
        txtHargaJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaJualActionPerformed(evt);
            }
        });
        jPanel2.add(txtHargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 440, 320, 30));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, -1));

        txtStok.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtStok.setBorder(null);
        txtStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokActionPerformed(evt);
            }
        });
        jPanel2.add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 503, 320, 30));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, -1, -1));

        txtStokMinimum.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtStokMinimum.setBorder(null);
        txtStokMinimum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokMinimumActionPerformed(evt);
            }
        });
        jPanel2.add(txtStokMinimum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 568, 330, 30));

        btnSimpan.setBorderPainted(false);
        btnSimpan.setContentAreaFilled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 660, 150, 30));

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 660, 160, 30));

        BG_FormProduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Tambah Produk.png"))); // NOI18N
        jPanel2.add(BG_FormProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // Ambil semua data dari form (kecuali barcode untuk produk baru)
        String nama = txtNamaProduk.getText();
        KategoriItem selectedKategori = (KategoriItem) cmbKategori.getSelectedItem();

        if (nama.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama produk tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int idKategori = selectedKategori.getId();

        Connection conn = null;
        try {
            conn = koneksi.getKoneksi();
            conn.setAutoCommit(false); // Mulai mode transaksi

            if (this.productId == 0) { // Mode Tambah (Logika Baru)
                String sqlInsert = "INSERT INTO PRODUK (nama_produk, id_kategori, harga_beli, harga_jual, jumlah_stok, stok_minimum) VALUES (?, ?, ?, ?, ?, ?)";
                PreparedStatement pstmtInsert = conn.prepareStatement(sqlInsert, Statement.RETURN_GENERATED_KEYS);

                pstmtInsert.setString(1, nama);
                pstmtInsert.setInt(2, idKategori);
                pstmtInsert.setDouble(3, Double.parseDouble(txtHargaBeli.getText()));
                pstmtInsert.setDouble(4, Double.parseDouble(txtHargaJual.getText()));
                pstmtInsert.setInt(5, Integer.parseInt(txtStok.getText()));
                pstmtInsert.setInt(6, Integer.parseInt(txtStokMinimum.getText()));

                pstmtInsert.executeUpdate();

                // LANGKAH 2: Ambil ID yang baru saja dibuat
                ResultSet generatedKeys = pstmtInsert.getGeneratedKeys();
                int newProductId;
                if (generatedKeys.next()) {
                    newProductId = generatedKeys.getInt(1);
                } else {
                    throw new SQLException("Gagal mendapatkan ID produk baru.");
                }

                // LANGKAH 3: Buat kode barcode berdasarkan ID
                // Contoh format: P000001, P000002, dst.
                String newBarcode = String.format("P%06d", newProductId);

                // LANGKAH 4: UPDATE produk dengan kode barcode baru
                String sqlUpdate = "UPDATE PRODUK SET kode_barcode = ? WHERE id_produk = ?";
                PreparedStatement pstmtUpdate = conn.prepareStatement(sqlUpdate);
                pstmtUpdate.setString(1, newBarcode);
                pstmtUpdate.setInt(2, newProductId);
                pstmtUpdate.executeUpdate();

            } else { // Mode Edit (Logika Lama, tetap sama)
                String sql = "UPDATE PRODUK SET nama_produk=?, id_kategori=?, kode_barcode=?, harga_beli=?, harga_jual=?, jumlah_stok=?, stok_minimum=? WHERE id_produk=?";
                PreparedStatement pstmt = conn.prepareStatement(sql);
                // Set parameter
                pstmt.setString(1, nama);
                pstmt.setInt(2, idKategori); // Update ID kategori
                pstmt.setString(3, txtBarcode.getText());
                pstmt.setDouble(4, Double.parseDouble(txtHargaBeli.getText()));
                pstmt.setDouble(5, Double.parseDouble(txtHargaJual.getText()));
                pstmt.setInt(6, Integer.parseInt(txtStok.getText()));
                pstmt.setInt(7, Integer.parseInt(txtStokMinimum.getText()));
                pstmt.setInt(8, this.productId);

                pstmt.executeUpdate();
            }

            conn.commit(); // Konfirmasi semua perubahan jika berhasil
            JOptionPane.showMessageDialog(this, "Data produk berhasil disimpan!");
            this.dispose();

        } catch (Exception e) {
            try {
                if (conn != null) {
                    conn.rollback(); // Batalkan transaksi jika ada error
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (conn != null) {
                    conn.setAutoCommit(true); // Kembalikan ke mode auto-commit
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtHargaBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaBeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaBeliActionPerformed

    private void txtHargaJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaJualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaJualActionPerformed

    private void txtStokMinimumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokMinimumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokMinimumActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ProdukForm PMForm = new ProdukForm(); PMForm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdukFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdukFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdukFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdukFormDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_FormProduk;
    private javax.swing.JToggleButton btnSimpan;
    private javax.swing.JComboBox<KategoriItem> cmbKategori;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtHargaBeli;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtNamaProduk;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtStokMinimum;
    // End of variables declaration//GEN-END:variables
}
