/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pelaporan;
import util.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lenovo
 */
public class LaporanPenjualanForm extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    /**
     * Creates new form LaporanPenjualanForm
     */
    public LaporanPenjualanForm() {
        initComponents();
        
        this.setLocationRelativeTo(null); // Form di tengah layar

        // Konfigurasi table model
        tableModel = new DefaultTableModel(
            new Object[]{"Bulan", "Jumlah Transaksi", "Total Penjualan"}, 0
        );
        tabelLaporan.setModel(tableModel);

        // Muat data untuk tahun saat ini ketika form pertama kali dibuka
        loadDataLaporan();
    }
    
    private void loadDataLaporan() {
        // Kosongkan tabel sebelum memuat data baru
        tableModel.setRowCount(0);
        
        // Dapatkan tahun yang dipilih dari JYearChooser
        int tahun = yearChooser.getYear();

        // Query untuk laporan bulanan
        String sqlLaporan = "SELECT MONTHNAME(tanggal_transaksi) AS bulan, "
                          + "COUNT(id_transaksi) AS jumlah_transaksi, "
                          + "SUM(harga_akhir) AS total_penjualan "
                          + "FROM transaksi "
                          + "WHERE YEAR(tanggal_transaksi) = ? "
                          + "GROUP BY YEAR(tanggal_transaksi), MONTH(tanggal_transaksi), MONTHNAME(tanggal_transaksi) "
                          + "ORDER BY MONTH(tanggal_transaksi) ASC";
        
        // Query untuk total tahunan
        String sqlTotal = "SELECT SUM(harga_akhir) FROM transaksi WHERE YEAR(tanggal_transaksi) = ?";

        // Format untuk menampilkan angka sebagai mata uang Rupiah (Rp)
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));

        try (Connection conn = koneksi.getKoneksi();
             PreparedStatement psLaporan = conn.prepareStatement(sqlLaporan);
             PreparedStatement psTotal = conn.prepareStatement(sqlTotal)) {

            // Set parameter tahun untuk kedua query
            psLaporan.setInt(1, tahun);
            psTotal.setInt(1, tahun);

            // 1. Eksekusi query untuk data bulanan dan isi tabel
            try (ResultSet rs = psLaporan.executeQuery()) {
                while (rs.next()) {
                    String bulan = rs.getString("bulan");
                    int jumlahTransaksi = rs.getInt("jumlah_transaksi");
                    double totalPenjualan = rs.getDouble("total_penjualan");

                    Object[] row = {
                        bulan,
                        jumlahTransaksi,
                        currencyFormat.format(totalPenjualan) // Format sebagai mata uang
                    };
                    tableModel.addRow(row);
                }
            }
            
            // 2. Eksekusi query untuk total penjualan tahunan
            try (ResultSet rsTotal = psTotal.executeQuery()) {
                if (rsTotal.next()) {
                    double totalTahunan = rsTotal.getDouble(1);
                    lblTotalTahunan.setText("Total Penjualan Tahun " + tahun + ": " + currencyFormat.format(totalTahunan));
                } else {
                    lblTotalTahunan.setText("Total Penjualan Tahun " + tahun + ": Rp 0,00");
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal mengambil data laporan: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        yearChooser = new com.toedter.calendar.JYearChooser();
        btnTampilkan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelLaporan = new javax.swing.JTable();
        lblTotalTahunan = new javax.swing.JLabel();
        BG_LaporanPenjualan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pilih Tahun");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        yearChooser.setFocusable(false);
        yearChooser.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jPanel1.add(yearChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 210, 50));

        btnTampilkan.setBorderPainted(false);
        btnTampilkan.setContentAreaFilled(false);
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });
        jPanel1.add(btnTampilkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, 350, 60));

        tabelLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelLaporan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 1040, -1));

        lblTotalTahunan.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jPanel1.add(lblTotalTahunan, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 390, 40));

        BG_LaporanPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Laporan Penjualan.png"))); // NOI18N
        jPanel1.add(BG_LaporanPenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        // TODO add your handling code here:
        loadDataLaporan();
    }//GEN-LAST:event_btnTampilkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPenjualanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPenjualanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_LaporanPenjualan;
    private javax.swing.JButton btnTampilkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalTahunan;
    private javax.swing.JTable tabelLaporan;
    private com.toedter.calendar.JYearChooser yearChooser;
    // End of variables declaration//GEN-END:variables
}
