package Pelaporan;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Lenovo
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import util.koneksi;

public class LaporanKeuanganForm extends javax.swing.JFrame {

    /**
     * Creates new form LaporanKeuanganForm
     */
    public LaporanKeuanganForm() {
        initComponents();

        this.setLocationRelativeTo(null);

        // Set tanggal default ke hari ini
        dateChooserMulai.setDate(new Date());
        dateChooserSelesai.setDate(new Date());

        // Langsung tampilkan laporan untuk hari ini saat form dibuka
        loadLaporanKeuangan();
    }

    private void loadLaporanKeuangan() {
        Date tanggalMulai = dateChooserMulai.getDate();
        Date tanggalSelesai = dateChooserSelesai.getDate();

        if (tanggalMulai == null || tanggalSelesai == null) {
            JOptionPane.showMessageDialog(this, "Tanggal mulai dan selesai harus diisi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String startDate = sdf.format(tanggalMulai);
        String endDate = sdf.format(tanggalSelesai);

        double pendapatan = 0;
        double hpp = 0;
        double labaKotor = 0;
        double pengeluaran = 0;

        // Definisikan query
        String sqlPendapatan = "SELECT IFNULL(SUM(harga_akhir), 0) FROM transaksi WHERE CAST(tanggal_transaksi AS DATE) BETWEEN ? AND ?";
        String sqlHpp = "SELECT IFNULL(SUM(dt.jumlah * p.harga_beli), 0) FROM detail_transaksi dt "
                + "JOIN produk p ON dt.id_produk = p.id_produk "
                + "JOIN transaksi t ON dt.id_transaksi = t.id_transaksi "
                + "WHERE CAST(t.tanggal_transaksi AS DATE) BETWEEN ? AND ?";
        String sqlPengeluaran = "SELECT IFNULL(SUM(total_harga), 0) FROM pembelian WHERE CAST(tanggal_beli AS DATE) BETWEEN ? AND ?";

        try (Connection conn = koneksi.getKoneksi()) {
            // 1. Ambil Total Pendapatan
            try (PreparedStatement ps = conn.prepareStatement(sqlPendapatan)) {
                ps.setString(1, startDate);
                ps.setString(2, endDate);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    pendapatan = rs.getDouble(1);
                }
            }

            // 2. Ambil Total HPP
            try (PreparedStatement ps = conn.prepareStatement(sqlHpp)) {
                ps.setString(1, startDate);
                ps.setString(2, endDate);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    hpp = rs.getDouble(1);
                }
            }

            // 3. Ambil Total Pengeluaran (Pembelian)
            try (PreparedStatement ps = conn.prepareStatement(sqlPengeluaran)) {
                ps.setString(1, startDate);
                ps.setString(2, endDate);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    pengeluaran = rs.getDouble(1);
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat laporan keuangan: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

        // Hitung Laba Kotor
        labaKotor = pendapatan - hpp;

        // Format nilai ke format mata uang Rupiah
        NumberFormat currencyFormat = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));

        // Tampilkan hasil ke JLabel
        lblPendapatan.setText(currencyFormat.format(pendapatan));
        lblHpp.setText(currencyFormat.format(hpp));
        lblLabaKotor.setText(currencyFormat.format(labaKotor));
        lblPengeluaran.setText(currencyFormat.format(pengeluaran));

        // Ubah warna label laba kotor
        if (labaKotor < 0) {
            lblLabaKotor.setForeground(java.awt.Color.RED);
        } else {
            lblLabaKotor.setForeground(new java.awt.Color(0, 153, 0)); // Warna hijau tua
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dateChooserMulai = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dateChooserSelesai = new com.toedter.calendar.JDateChooser();
        btnTampilkan = new javax.swing.JButton();
        lblPendapatan = new javax.swing.JLabel();
        lblHpp = new javax.swing.JLabel();
        lblLabaKotor = new javax.swing.JLabel();
        lblPengeluaran = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BG_LaporanKeuangan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        dateChooserMulai.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(dateChooserMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 240, 40));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        dateChooserSelesai.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(dateChooserSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 240, 40));

        btnTampilkan.setBorderPainted(false);
        btnTampilkan.setContentAreaFilled(false);
        btnTampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilkanActionPerformed(evt);
            }
        });
        jPanel1.add(btnTampilkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 340, 60));

        lblPendapatan.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblPendapatan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblPendapatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 370, 60));

        lblHpp.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblHpp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblHpp, new org.netbeans.lib.awtextra.AbsoluteConstraints(837, 856, 370, 60));

        lblLabaKotor.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblLabaKotor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblLabaKotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 660, 380, 60));

        lblPengeluaran.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblPengeluaran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblPengeluaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 456, 380, 50));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, -1, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 410, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 610, -1, -1));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 820, -1, -1));

        BG_LaporanKeuangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Laporan Keuangan.png"))); // NOI18N
        jPanel1.add(BG_LaporanKeuangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilkanActionPerformed
        // TODO add your handling code here:
        loadLaporanKeuangan();
    }//GEN-LAST:event_btnTampilkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuanganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuanganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuanganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuanganForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanKeuanganForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG_LaporanKeuangan;
    private javax.swing.JButton btnTampilkan;
    private com.toedter.calendar.JDateChooser dateChooserMulai;
    private com.toedter.calendar.JDateChooser dateChooserSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHpp;
    private javax.swing.JLabel lblLabaKotor;
    private javax.swing.JLabel lblPendapatan;
    private javax.swing.JLabel lblPengeluaran;
    // End of variables declaration//GEN-END:variables
}
